function launch_gui()
% launch_gui launches the LPR and SIS graphical user interface.

    addpath(genpath('src'));
    ensureOutputFolders();

    % Initialize state
    state.originalImg = [];
    state.plateImg = [];
    state.cleanedText = "UNKNOWN";
    state.stateName = "UNKNOWN";
    state.imagePath = "";

    % Create main figure
    fig = figure( ...
        'Name', 'LPR and SIS - License Plate Recognition System', ...
        'NumberTitle', 'off', ...
        'Position', [80, 80, 1100, 680], ...
        'Color', [0.95 0.95 0.97]);

    % Title bar
    uicontrol('Style', 'text', ...
        'Units', 'normalized', ...
        'Position', [0.0, 0.93, 1.0, 0.07], ...
        'String', 'License Plate Recognition and State Identification System', ...
        'FontSize', 14, ...
        'FontWeight', 'bold', ...
        'ForegroundColor', [1 1 1], ...
        'BackgroundColor', [0.15 0.35 0.60]);

    % Buttons
    uicontrol('Style', 'pushbutton', ...
        'String', 'Load Image', ...
        'Units', 'normalized', ...
        'Position', [0.03, 0.85, 0.15, 0.06], ...
        'FontSize', 11, ...
        'FontWeight', 'bold', ...
        'BackgroundColor', [0.25 0.55 0.85], ...
        'ForegroundColor', [1 1 1], ...
        'Callback', @onLoadImage);

    uicontrol('Style', 'pushbutton', ...
        'String', 'Run Recognition', ...
        'Units', 'normalized', ...
        'Position', [0.20, 0.85, 0.18, 0.06], ...
        'FontSize', 11, ...
        'FontWeight', 'bold', ...
        'BackgroundColor', [0.15 0.65 0.35], ...
        'ForegroundColor', [1 1 1], ...
        'Callback', @onRunRecognition);

    % Image axes
    axOriginal = axes('Parent', fig, ...
        'Units', 'normalized', ...
        'Position', [0.03, 0.28, 0.44, 0.54]);
    title(axOriginal, 'Original Image', 'FontSize', 11, 'FontWeight', 'bold');
    axis(axOriginal, 'off');

    axPlate = axes('Parent', fig, ...
        'Units', 'normalized', ...
        'Position', [0.53, 0.28, 0.44, 0.54]);
    title(axPlate, 'Detected Plate', 'FontSize', 11, 'FontWeight', 'bold');
    axis(axPlate, 'off');

    % Result panel background
    uicontrol('Style', 'text', ...
        'Units', 'normalized', ...
        'Position', [0.03, 0.03, 0.94, 0.23], ...
        'String', '', ...
        'BackgroundColor', [0.88 0.92 0.98]);

    % Result labels
    uicontrol('Style', 'text', ...
        'Units', 'normalized', ...
        'Position', [0.05, 0.17, 0.15, 0.05], ...
        'String', 'Plate Text:', ...
        'FontSize', 11, ...
        'FontWeight', 'bold', ...
        'HorizontalAlignment', 'left', ...
        'BackgroundColor', [0.88 0.92 0.98]);

    uicontrol('Style', 'text', ...
        'Units', 'normalized', ...
        'Position', [0.05, 0.11, 0.15, 0.05], ...
        'String', 'State:', ...
        'FontSize', 11, ...
        'FontWeight', 'bold', ...
        'HorizontalAlignment', 'left', ...
        'BackgroundColor', [0.88 0.92 0.98]);

    uicontrol('Style', 'text', ...
        'Units', 'normalized', ...
        'Position', [0.05, 0.05, 0.15, 0.05], ...
        'String', 'Status:', ...
        'FontSize', 11, ...
        'FontWeight', 'bold', ...
        'HorizontalAlignment', 'left', ...
        'BackgroundColor', [0.88 0.92 0.98]);

    % Result value fields
    txtRecognized = uicontrol('Style', 'text', ...
        'Units', 'normalized', ...
        'Position', [0.21, 0.17, 0.74, 0.05], ...
        'String', 'UNKNOWN', ...
        'FontSize', 12, ...
        'FontWeight', 'bold', ...
        'HorizontalAlignment', 'left', ...
        'ForegroundColor', [0.7 0.1 0.1], ...
        'BackgroundColor', [0.88 0.92 0.98]);

    txtState = uicontrol('Style', 'text', ...
        'Units', 'normalized', ...
        'Position', [0.21, 0.11, 0.74, 0.05], ...
        'String', 'UNKNOWN', ...
        'FontSize', 12, ...
        'FontWeight', 'bold', ...
        'HorizontalAlignment', 'left', ...
        'ForegroundColor', [0.7 0.1 0.1], ...
        'BackgroundColor', [0.88 0.92 0.98]);

    txtStatus = uicontrol('Style', 'text', ...
        'Units', 'normalized', ...
        'Position', [0.21, 0.05, 0.74, 0.05], ...
        'String', 'Ready. Please load an image.', ...
        'FontSize', 10, ...
        'HorizontalAlignment', 'left', ...
        'ForegroundColor', [0.2 0.2 0.2], ...
        'BackgroundColor', [0.88 0.92 0.98]);

    % Store UI handles
    ui.axOriginal = axOriginal;
    ui.axPlate = axPlate;
    ui.txtRecognized = txtRecognized;
    ui.txtState = txtState;
    ui.txtStatus = txtStatus;
    ui.data = state;
    guidata(fig, ui);

    % Load Image callback
    function onLoadImage(~, ~)
        uiLocal = guidata(fig);
        [fileName, pathName] = uigetfile({'*.jpg;*.jpeg;*.png;*.bmp', 'Image Files'});
        if isequal(fileName, 0)
            set(uiLocal.txtStatus, 'String', 'Image selection cancelled.');
            return;
        end
        selectedPath = fullfile(pathName, fileName);
        try
            img = imread(selectedPath);
            uiLocal.data.originalImg = img;
            uiLocal.data.imagePath = string(selectedPath);
            axes(uiLocal.axOriginal); %#ok<LAXES>
            imshow(img);
            title(uiLocal.axOriginal, 'Original Image', 'FontSize', 11, 'FontWeight', 'bold');
            cla(uiLocal.axPlate);
            title(uiLocal.axPlate, 'Detected Plate', 'FontSize', 11, 'FontWeight', 'bold');
            set(uiLocal.txtRecognized, 'String', 'UNKNOWN', 'ForegroundColor', [0.7 0.1 0.1]);
            set(uiLocal.txtState, 'String', 'UNKNOWN', 'ForegroundColor', [0.7 0.1 0.1]);
            set(uiLocal.txtStatus, 'String', 'Image loaded successfully. Click Run Recognition.');
        catch loadErr
            set(uiLocal.txtStatus, 'String', 'Failed to load image. Please try again.');
            warning('Failed to load image: %s', loadErr.message);
        end
        guidata(fig, uiLocal);
    end

    % Run Recognition callback
    function onRunRecognition(~, ~)
        uiLocal = guidata(fig);
        if isempty(uiLocal.data.originalImg)
            set(uiLocal.txtStatus, 'String', 'Please load an image first.');
            return;
        end
        set(uiLocal.txtStatus, 'String', 'Running recognition. Please wait...');
        drawnow;
        try
            [preprocessedImg, ~] = preprocessImage(uiLocal.data.originalImg);
            [plateImg, ~, ~] = detectPlateRegion(preprocessedImg, uiLocal.data.originalImg);
            [~, ~] = segmentCharacters(plateImg);
            rawText = recognizePlateText(plateImg);
            cleanedText = cleanRecognizedText(rawText);
            stateNameLocal = identifyState(cleanedText);

            uiLocal.data.plateImg = plateImg;
            uiLocal.data.cleanedText = cleanedText;
            uiLocal.data.stateName = stateNameLocal;

            if ~isempty(plateImg)
                axes(uiLocal.axPlate); %#ok<LAXES>
                imshow(plateImg);
                title(uiLocal.axPlate, 'Detected Plate', 'FontSize', 11, 'FontWeight', 'bold');
            else
                cla(uiLocal.axPlate);
                title(uiLocal.axPlate, 'Detected Plate (Not Found)', 'FontSize', 11);
            end

            if cleanedText ~= "UNKNOWN"
                set(uiLocal.txtRecognized, 'String', cleanedText, 'ForegroundColor', [0.1 0.5 0.1]);
            else
                set(uiLocal.txtRecognized, 'String', 'UNKNOWN', 'ForegroundColor', [0.7 0.1 0.1]);
            end

            if stateNameLocal ~= "UNKNOWN"
                set(uiLocal.txtState, 'String', stateNameLocal, 'ForegroundColor', [0.1 0.5 0.1]);
            else
                set(uiLocal.txtState, 'String', 'UNKNOWN', 'ForegroundColor', [0.7 0.1 0.1]);
            end

            set(uiLocal.txtStatus, 'String', 'Recognition completed successfully.');

        catch runErr
            set(uiLocal.txtStatus, 'String', 'Recognition failed. Check Command Window for details.');
            warning('Recognition error: %s', runErr.message);
        end
        guidata(fig, uiLocal);
    end

end