function launch_gui()
% launch_gui launches the LPR and SIS graphical user interface.

    addpath(genpath('src'));
    paths = ensureOutputFolders();

    % Initialize state
    state.originalImg = [];
    state.plateImg = [];
    state.plateBBox = [];
    state.detectionDebug = struct();
    state.segmentationDebug = struct();
    state.ocrDebug = struct();
    state.rawText = "UNKNOWN";
    state.cleanedText = "UNKNOWN";
    state.stateName = "UNKNOWN";
    state.imagePath = "";
    state.guiResultsCsv = string(paths.guiResultsCsv);

    % Create main figure
    fig = figure( ...
        'Name', 'LPR and SIS - License Plate Recognition System', ...
        'NumberTitle', 'off', ...
        'Position', [80, 80, 1100, 680], ...
        'Color', [0.95 0.95 0.97]);

    % Title bar
    uicontrol('Style', 'text', ...
        'Units', 'normalized', ...
        'Position', [0.0, 0.93, 1.0, 0.07], ...
        'String', 'License Plate Recognition and State Identification System', ...
        'FontSize', 14, ...
        'FontWeight', 'bold', ...
        'ForegroundColor', [1 1 1], ...
        'BackgroundColor', [0.15 0.35 0.60]);

    % Buttons
    uicontrol('Style', 'pushbutton', ...
        'String', 'Load Image', ...
        'Units', 'normalized', ...
        'Position', [0.03, 0.85, 0.15, 0.06], ...
        'FontSize', 11, ...
        'FontWeight', 'bold', ...
        'BackgroundColor', [0.25 0.55 0.85], ...
        'ForegroundColor', [1 1 1], ...
        'Callback', @onLoadImage);

    uicontrol('Style', 'pushbutton', ...
        'String', 'Run Recognition', ...
        'Units', 'normalized', ...
        'Position', [0.20, 0.85, 0.18, 0.06], ...
        'FontSize', 11, ...
        'FontWeight', 'bold', ...
        'BackgroundColor', [0.15 0.65 0.35], ...
        'ForegroundColor', [1 1 1], ...
        'Callback', @onRunRecognition);

    % Image axes
    axOriginal = axes('Parent', fig, ...
        'Units', 'normalized', ...
        'Position', [0.03, 0.28, 0.44, 0.54]);
    title(axOriginal, 'Original Image', 'FontSize', 11, 'FontWeight', 'bold');
    axis(axOriginal, 'off');

    axPlate = axes('Parent', fig, ...
        'Units', 'normalized', ...
        'Position', [0.53, 0.28, 0.44, 0.54]);
    title(axPlate, 'Detected Plate', 'FontSize', 11, 'FontWeight', 'bold');
    axis(axPlate, 'off');

    % Result panel background
    uicontrol('Style', 'text', ...
        'Units', 'normalized', ...
        'Position', [0.03, 0.03, 0.94, 0.23], ...
        'String', '', ...
        'BackgroundColor', [0.88 0.92 0.98]);

    % Result labels
    uicontrol('Style', 'text', ...
        'Units', 'normalized', ...
        'Position', [0.05, 0.17, 0.15, 0.05], ...
        'String', 'Plate Text:', ...
        'FontSize', 11, ...
        'FontWeight', 'bold', ...
        'HorizontalAlignment', 'left', ...
        'BackgroundColor', [0.88 0.92 0.98]);

    uicontrol('Style', 'text', ...
        'Units', 'normalized', ...
        'Position', [0.05, 0.11, 0.15, 0.05], ...
        'String', 'State:', ...
        'FontSize', 11, ...
        'FontWeight', 'bold', ...
        'HorizontalAlignment', 'left', ...
        'BackgroundColor', [0.88 0.92 0.98]);

    uicontrol('Style', 'text', ...
        'Units', 'normalized', ...
        'Position', [0.05, 0.05, 0.15, 0.05], ...
        'String', 'Status:', ...
        'FontSize', 11, ...
        'FontWeight', 'bold', ...
        'HorizontalAlignment', 'left', ...
        'BackgroundColor', [0.88 0.92 0.98]);

    % Result value fields
    txtRecognized = uicontrol('Style', 'text', ...
        'Units', 'normalized', ...
        'Position', [0.21, 0.17, 0.74, 0.05], ...
        'String', 'UNKNOWN', ...
        'FontSize', 12, ...
        'FontWeight', 'bold', ...
        'HorizontalAlignment', 'left', ...
        'ForegroundColor', [0.7 0.1 0.1], ...
        'BackgroundColor', [0.88 0.92 0.98]);

    txtState = uicontrol('Style', 'text', ...
        'Units', 'normalized', ...
        'Position', [0.21, 0.11, 0.74, 0.05], ...
        'String', 'UNKNOWN', ...
        'FontSize', 12, ...
        'FontWeight', 'bold', ...
        'HorizontalAlignment', 'left', ...
        'ForegroundColor', [0.7 0.1 0.1], ...
        'BackgroundColor', [0.88 0.92 0.98]);

    txtStatus = uicontrol('Style', 'text', ...
        'Units', 'normalized', ...
        'Position', [0.21, 0.05, 0.74, 0.05], ...
        'String', 'Ready. Please load an image.', ...
        'FontSize', 10, ...
        'HorizontalAlignment', 'left', ...
        'ForegroundColor', [0.2 0.2 0.2], ...
        'BackgroundColor', [0.88 0.92 0.98]);

    % Debug/log path panel
    uicontrol('Style', 'text', ...
        'Units', 'normalized', ...
        'Position', [0.03, 0.095, 0.19, 0.03], ...
        'String', 'Detection Debug Folder:', ...
        'FontSize', 9, ...
        'HorizontalAlignment', 'left', ...
        'BackgroundColor', [0.88 0.92 0.98]);
    txtDetectDir = uicontrol('Style', 'text', ...
        'Units', 'normalized', ...
        'Position', [0.21, 0.095, 0.76, 0.03], ...
        'String', 'Not available', ...
        'FontSize', 8, ...
        'HorizontalAlignment', 'left', ...
        'BackgroundColor', [0.88 0.92 0.98]);

    uicontrol('Style', 'text', ...
        'Units', 'normalized', ...
        'Position', [0.03, 0.070, 0.19, 0.03], ...
        'String', 'Segmentation Debug Folder:', ...
        'FontSize', 9, ...
        'HorizontalAlignment', 'left', ...
        'BackgroundColor', [0.88 0.92 0.98]);
    txtSegDir = uicontrol('Style', 'text', ...
        'Units', 'normalized', ...
        'Position', [0.21, 0.070, 0.76, 0.03], ...
        'String', 'Not available', ...
        'FontSize', 8, ...
        'HorizontalAlignment', 'left', ...
        'BackgroundColor', [0.88 0.92 0.98]);

    uicontrol('Style', 'text', ...
        'Units', 'normalized', ...
        'Position', [0.03, 0.045, 0.19, 0.03], ...
        'String', 'Recognition Debug Folder:', ...
        'FontSize', 9, ...
        'HorizontalAlignment', 'left', ...
        'BackgroundColor', [0.88 0.92 0.98]);
    txtRecDir = uicontrol('Style', 'text', ...
        'Units', 'normalized', ...
        'Position', [0.21, 0.045, 0.76, 0.03], ...
        'String', 'Not available', ...
        'FontSize', 8, ...
        'HorizontalAlignment', 'left', ...
        'BackgroundColor', [0.88 0.92 0.98]);

    uicontrol('Style', 'text', ...
        'Units', 'normalized', ...
        'Position', [0.03, 0.020, 0.19, 0.03], ...
        'String', 'GUI Results CSV:', ...
        'FontSize', 9, ...
        'HorizontalAlignment', 'left', ...
        'BackgroundColor', [0.88 0.92 0.98]);
    txtGuiCsv = uicontrol('Style', 'text', ...
        'Units', 'normalized', ...
        'Position', [0.21, 0.020, 0.76, 0.03], ...
        'String', char(state.guiResultsCsv), ...
        'FontSize', 8, ...
        'HorizontalAlignment', 'left', ...
        'BackgroundColor', [0.88 0.92 0.98]);

    % Open-folder buttons
    uicontrol('Style', 'pushbutton', ...
        'String', 'Open Detection Log', ...
        'Units', 'normalized', ...
        'Position', [0.40, 0.85, 0.13, 0.06], ...
        'FontSize', 10, ...
        'Callback', @onOpenDetectionLog);
    uicontrol('Style', 'pushbutton', ...
        'String', 'Open Segmentation Log', ...
        'Units', 'normalized', ...
        'Position', [0.54, 0.85, 0.13, 0.06], ...
        'FontSize', 10, ...
        'Callback', @onOpenSegmentationLog);
    uicontrol('Style', 'pushbutton', ...
        'String', 'Open Recognition Log', ...
        'Units', 'normalized', ...
        'Position', [0.68, 0.85, 0.13, 0.06], ...
        'FontSize', 10, ...
        'Callback', @onOpenRecognitionLog);
    uicontrol('Style', 'pushbutton', ...
        'String', 'Open Report Tables', ...
        'Units', 'normalized', ...
        'Position', [0.82, 0.85, 0.15, 0.06], ...
        'FontSize', 10, ...
        'Callback', @onOpenReportTables);

    % Store UI handles
    ui.axOriginal = axOriginal;
    ui.axPlate = axPlate;
    ui.txtRecognized = txtRecognized;
    ui.txtState = txtState;
    ui.txtStatus = txtStatus;
    ui.txtDetectDir = txtDetectDir;
    ui.txtSegDir = txtSegDir;
    ui.txtRecDir = txtRecDir;
    ui.txtGuiCsv = txtGuiCsv;
    ui.paths = paths;
    ui.data = state;
    guidata(fig, ui);

    % Load Image callback
    function onLoadImage(~, ~)
        uiLocal = guidata(fig);
        [fileName, pathName] = uigetfile({'*.jpg;*.jpeg;*.png;*.bmp', 'Image Files'});
        if isequal(fileName, 0)
            set(uiLocal.txtStatus, 'String', 'Image selection cancelled.');
            return;
        end
        selectedPath = fullfile(pathName, fileName);
        try
            img = imread(selectedPath);
            uiLocal.data.originalImg = img;
            uiLocal.data.imagePath = string(selectedPath);
            uiLocal.data.plateBBox = [];
            uiLocal.data.detectionDebug = struct();
            uiLocal.data.segmentationDebug = struct();
            uiLocal.data.ocrDebug = struct();
            uiLocal.data.rawText = "UNKNOWN";
            uiLocal.data.cleanedText = "UNKNOWN";
            uiLocal.data.stateName = "UNKNOWN";
            axes(uiLocal.axOriginal); %#ok<LAXES>
            imshow(img);
            title(uiLocal.axOriginal, 'Original Image', 'FontSize', 11, 'FontWeight', 'bold');
            cla(uiLocal.axPlate);
            title(uiLocal.axPlate, 'Detected Plate', 'FontSize', 11, 'FontWeight', 'bold');
            set(uiLocal.txtRecognized, 'String', 'UNKNOWN', 'ForegroundColor', [0.7 0.1 0.1]);
            set(uiLocal.txtState, 'String', 'UNKNOWN', 'ForegroundColor', [0.7 0.1 0.1]);
            set(uiLocal.txtDetectDir, 'String', 'Not available');
            set(uiLocal.txtSegDir, 'String', 'Not available');
            set(uiLocal.txtRecDir, 'String', 'Not available');
            set(uiLocal.txtGuiCsv, 'String', char(uiLocal.data.guiResultsCsv));
            set(uiLocal.txtStatus, 'String', 'Image loaded successfully. Click Run Recognition.');
        catch loadErr
            set(uiLocal.txtStatus, 'String', 'Failed to load image. Please try again.');
            warning('Failed to load image: %s', loadErr.message);
        end
        guidata(fig, uiLocal);
    end

    % Run Recognition callback
    function onRunRecognition(~, ~)
        uiLocal = guidata(fig);
        if isempty(uiLocal.data.originalImg)
            set(uiLocal.txtStatus, 'String', 'Please load an image first.');
            return;
        end
        set(uiLocal.txtStatus, 'String', 'Running recognition. Please wait...');
        drawnow;

        pipelineNotes = "Pipeline completed.";
        detectionResult = "Failure";
        ocrResult = "Not Evaluated";
        stateResult = "Not Evaluated";
        overallResult = "Completed";
        rawText = "UNKNOWN";
        cleanedText = "UNKNOWN";
        stateNameLocal = "UNKNOWN";
        plateImg = [];
        plateBBox = [];
        detectionDebug = struct();
        segmentationDebug = struct();
        ocrDebug = struct();

        try
            [preprocessedImg, ~] = preprocessImage(uiLocal.data.originalImg);
            [plateImg, plateBBox, detectionDebug] = detectPlateRegion(preprocessedImg, uiLocal.data.originalImg);

            if ~isempty(plateImg)
                detectionResult = "Success";
                [~, ~, segmentationDebug] = segmentCharacters(plateImg);
                [rawText, ocrDebug] = recognizePlateText(plateImg);
                cleanedText = cleanRecognizedText(rawText);
                stateNameLocal = identifyState(cleanedText);
            else
                detectionResult = "Failure";
                pipelineNotes = "Detection failed: plate image is empty.";
            end

            uiLocal.data.plateImg = plateImg;
            uiLocal.data.plateBBox = plateBBox;
            uiLocal.data.detectionDebug = detectionDebug;
            uiLocal.data.segmentationDebug = segmentationDebug;
            uiLocal.data.ocrDebug = ocrDebug;
            uiLocal.data.rawText = rawText;
            uiLocal.data.cleanedText = cleanedText;
            uiLocal.data.stateName = stateNameLocal;

            if ~isempty(plateImg)
                axes(uiLocal.axPlate); %#ok<LAXES>
                imshow(plateImg);
                title(uiLocal.axPlate, 'Detected Plate', 'FontSize', 11, 'FontWeight', 'bold');
            else
                cla(uiLocal.axPlate);
                title(uiLocal.axPlate, 'Detected Plate (Not Found)', 'FontSize', 11);
            end

            if cleanedText ~= "UNKNOWN"
                set(uiLocal.txtRecognized, 'String', cleanedText, 'ForegroundColor', [0.1 0.5 0.1]);
            else
                set(uiLocal.txtRecognized, 'String', 'UNKNOWN', 'ForegroundColor', [0.7 0.1 0.1]);
            end

            if stateNameLocal ~= "UNKNOWN"
                set(uiLocal.txtState, 'String', stateNameLocal, 'ForegroundColor', [0.1 0.5 0.1]);
            else
                set(uiLocal.txtState, 'String', 'UNKNOWN', 'ForegroundColor', [0.7 0.1 0.1]);
            end

            detectDir = localExtractDebugDir(detectionDebug, ["debugOutputDir", "outputDir"]);
            segDir = localExtractDebugDir(segmentationDebug, ["outputDir", "debugOutputDir"]);
            recDir = localExtractDebugDir(ocrDebug, ["outputDir", "debugOutputDir"]);
            set(uiLocal.txtDetectDir, 'String', char(detectDir));
            set(uiLocal.txtSegDir, 'String', char(segDir));
            set(uiLocal.txtRecDir, 'String', char(recDir));
            set(uiLocal.txtGuiCsv, 'String', char(uiLocal.data.guiResultsCsv));

            if cleanedText == "UNKNOWN"
                ocrResult = "Not Evaluated";
                stateResult = "Not Evaluated";
                if detectionResult == "Success"
                    pipelineNotes = "OCR returned UNKNOWN.";
                end
            end

            localAppendGuiResult(uiLocal, detectionResult, ocrResult, stateResult, overallResult, ...
                pipelineNotes, detectDir, segDir, recDir);
            set(uiLocal.txtStatus, 'String', 'Recognition completed successfully.');

        catch runErr
            pipelineNotes = "Recognition error: " + string(runErr.message);
            localAppendGuiResult(uiLocal, detectionResult, ocrResult, stateResult, overallResult, ...
                pipelineNotes, "Not available", "Not available", "Not available");
            set(uiLocal.txtStatus, 'String', 'Recognition failed. Check Command Window for details.');
            warning('Recognition error: %s', runErr.message);
        end
        guidata(fig, uiLocal);
    end

    function onOpenDetectionLog(~, ~)
        uiLocal = guidata(fig);
        p = localExtractDebugDir(uiLocal.data.detectionDebug, ["debugOutputDir", "outputDir"]);
        localOpenPathOrWarn(p, uiLocal.txtStatus, "Detection log folder is not available.");
    end

    function onOpenSegmentationLog(~, ~)
        uiLocal = guidata(fig);
        p = localExtractDebugDir(uiLocal.data.segmentationDebug, ["outputDir", "debugOutputDir"]);
        localOpenPathOrWarn(p, uiLocal.txtStatus, "Segmentation log folder is not available.");
    end

    function onOpenRecognitionLog(~, ~)
        uiLocal = guidata(fig);
        p = localExtractDebugDir(uiLocal.data.ocrDebug, ["outputDir", "debugOutputDir"]);
        localOpenPathOrWarn(p, uiLocal.txtStatus, "Recognition log folder is not available.");
    end

    function onOpenReportTables(~, ~)
        uiLocal = guidata(fig);
        localOpenPathOrWarn(uiLocal.paths.reportTables, uiLocal.txtStatus, "Report tables folder is not available.");
    end

    function localOpenPathOrWarn(pathValue, txtStatusHandle, missingMsg)
        p = string(pathValue);
        if strlength(p) == 0 || p == "Not available" || ~exist(char(p), 'dir')
            set(txtStatusHandle, 'String', missingMsg);
            return;
        end
        try
            winopen(char(p));
            set(txtStatusHandle, 'String', "Opened: " + p);
        catch
            set(txtStatusHandle, 'String', "Failed to open path: " + p);
        end
    end

    function dirValue = localExtractDebugDir(debugStruct, fieldPriority)
        dirValue = "Not available";
        if ~isstruct(debugStruct)
            return;
        end
        for idx = 1:numel(fieldPriority)
            fieldName = fieldPriority(idx);
            if isfield(debugStruct, fieldName)
                tmp = string(debugStruct.(fieldName));
                if strlength(tmp) > 0
                    dirValue = tmp;
                    return;
                end
            end
        end
    end

    function localAppendGuiResult(uiLocal, detectionResult, ocrResult, stateResult, overallResult, notes, detDir, segDir, recDir)
        csvPath = char(uiLocal.data.guiResultsCsv);
        [~, imageName, ext] = fileparts(char(uiLocal.data.imagePath));
        imageName = string(imageName) + string(ext);
        if strlength(imageName) == 0
            imageName = "UNKNOWN_IMAGE";
        end

        row = table( ...
            string(imageName), ...
            string(uiLocal.data.cleanedText), ...
            string(uiLocal.data.stateName), ...
            string(detectionResult), ...
            string(ocrResult), ...
            string(stateResult), ...
            string(overallResult), ...
            string(notes), ...
            string(detDir), ...
            string(segDir), ...
            string(recDir), ...
            'VariableNames', { ...
            'image_name','ocr_text','predicted_state','detection_result','ocr_result','state_result','overall_result', ...
            'notes','detection_debug_dir','segmentation_debug_dir','recognition_debug_dir'});

        try
            [csvDir, ~, ~] = fileparts(csvPath);
            if ~exist(csvDir, 'dir')
                mkdir(csvDir);
            end
            if ~isfile(csvPath)
                writetable(row, csvPath);
            else
                existing = readtable(csvPath, 'TextType', 'string');
                requiredCols = row.Properties.VariableNames;
                for i = 1:numel(requiredCols)
                    if ~ismember(requiredCols{i}, existing.Properties.VariableNames)
                        existing.(requiredCols{i}) = "";
                    end
                end
                existing = existing(:, requiredCols);
                writetable([existing; row], csvPath);
            end
        catch csvErr
            warning('GUI result CSV append failed: %s', csvErr.message);
        end
    end

end
